// <auto-generated />
using System;
using BiebCWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiebCWebsite.Migrations
{
    [DbContext(typeof(BiebCWebsiteContext))]
    [Migration("20230419094613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiebCWebsite.Models.AdminModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminModelId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeModelId")
                        .HasColumnType("int");

                    b.Property<int?>("GuestModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminModelId");

                    b.HasIndex("EmployeeModelId");

                    b.HasIndex("GuestModelId");

                    b.ToTable("BookModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.CDModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminModelId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeModelId")
                        .HasColumnType("int");

                    b.Property<int?>("GuestModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminModelId");

                    b.HasIndex("EmployeeModelId");

                    b.HasIndex("GuestModelId");

                    b.ToTable("CDModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminModelId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminModelId");

                    b.ToTable("EmployeeModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.GuestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminModelId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeModelId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminModelId");

                    b.HasIndex("EmployeeModelId");

                    b.ToTable("GuestModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminModelId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeModelId")
                        .HasColumnType("int");

                    b.Property<int?>("GuestModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminModelId");

                    b.HasIndex("EmployeeModelId");

                    b.HasIndex("GuestModelId");

                    b.ToTable("ItemModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.MovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminModelId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeModelId")
                        .HasColumnType("int");

                    b.Property<int?>("GuestModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminModelId");

                    b.HasIndex("EmployeeModelId");

                    b.HasIndex("GuestModelId");

                    b.ToTable("MovieModel");
                });

            modelBuilder.Entity("BiebCWebsite.Models.BookModel", b =>
                {
                    b.HasOne("BiebCWebsite.Models.AdminModel", null)
                        .WithMany("Books")
                        .HasForeignKey("AdminModelId");

                    b.HasOne("BiebCWebsite.Models.EmployeeModel", null)
                        .WithMany("Books")
                        .HasForeignKey("EmployeeModelId");

                    b.HasOne("BiebCWebsite.Models.GuestModel", null)
                        .WithMany("Books")
                        .HasForeignKey("GuestModelId");
                });

            modelBuilder.Entity("BiebCWebsite.Models.CDModel", b =>
                {
                    b.HasOne("BiebCWebsite.Models.AdminModel", null)
                        .WithMany("CDs")
                        .HasForeignKey("AdminModelId");

                    b.HasOne("BiebCWebsite.Models.EmployeeModel", null)
                        .WithMany("CDs")
                        .HasForeignKey("EmployeeModelId");

                    b.HasOne("BiebCWebsite.Models.GuestModel", null)
                        .WithMany("CDs")
                        .HasForeignKey("GuestModelId");
                });

            modelBuilder.Entity("BiebCWebsite.Models.EmployeeModel", b =>
                {
                    b.HasOne("BiebCWebsite.Models.AdminModel", null)
                        .WithMany("Employee")
                        .HasForeignKey("AdminModelId");
                });

            modelBuilder.Entity("BiebCWebsite.Models.GuestModel", b =>
                {
                    b.HasOne("BiebCWebsite.Models.AdminModel", null)
                        .WithMany("Guests")
                        .HasForeignKey("AdminModelId");

                    b.HasOne("BiebCWebsite.Models.EmployeeModel", null)
                        .WithMany("Guests")
                        .HasForeignKey("EmployeeModelId");
                });

            modelBuilder.Entity("BiebCWebsite.Models.ItemModel", b =>
                {
                    b.HasOne("BiebCWebsite.Models.AdminModel", null)
                        .WithMany("Items")
                        .HasForeignKey("AdminModelId");

                    b.HasOne("BiebCWebsite.Models.EmployeeModel", null)
                        .WithMany("Items")
                        .HasForeignKey("EmployeeModelId");

                    b.HasOne("BiebCWebsite.Models.GuestModel", null)
                        .WithMany("Items")
                        .HasForeignKey("GuestModelId");
                });

            modelBuilder.Entity("BiebCWebsite.Models.MovieModel", b =>
                {
                    b.HasOne("BiebCWebsite.Models.AdminModel", null)
                        .WithMany("Movies")
                        .HasForeignKey("AdminModelId");

                    b.HasOne("BiebCWebsite.Models.EmployeeModel", null)
                        .WithMany("Movies")
                        .HasForeignKey("EmployeeModelId");

                    b.HasOne("BiebCWebsite.Models.GuestModel", null)
                        .WithMany("Movies")
                        .HasForeignKey("GuestModelId");
                });

            modelBuilder.Entity("BiebCWebsite.Models.AdminModel", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("CDs");

                    b.Navigation("Employee");

                    b.Navigation("Guests");

                    b.Navigation("Items");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BiebCWebsite.Models.EmployeeModel", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("CDs");

                    b.Navigation("Guests");

                    b.Navigation("Items");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BiebCWebsite.Models.GuestModel", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("CDs");

                    b.Navigation("Items");

                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
